from datetime import datetime, UTC

from sqlalchemy.orm import mapped_column, Mapped
from sqlalchemy import Integer, String, Text, DateTime, ForeignKey

from database import Base

from enum import Enum


class MessageRole(Enum):
    USER = 0
    ASSISTANT = 1
    SYSTEM = 2
    OTHER = 3


class User(Base):
    __tablename__ = "users"
    id: Mapped[str] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    role: Mapped[int] = mapped_column(Integer, nullable=False)
    password_hash: Mapped[str] = mapped_column(String, nullable=False)
    token: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=datetime.now(UTC)
    )


class Project(Base):  # renamed from businesses to projects...
    __tablename__ = "projects"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    root_dir: Mapped[str] = mapped_column(String, nullable=False)
    agent_root_dir: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=datetime.now(UTC)
    )


class Message(Base):
    """
    AI/User Message
    """

    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    role: Mapped[MessageRole] = mapped_column(
        MessageRole, nullable=False
    )  # 0 - user, 1 - AI, 2 - system, 3 - other. maybe enum xd
    content: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=datetime.now(UTC)
    )

    chat_id: Mapped[int] = mapped_column(
        ForeignKey("chats.id"), nullable=False, index=True
    )


class Chat(Base):
    """A group of messages"""

    __tablename__ = "chats"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=datetime.now(UTC)
    )

    project_id: Mapped[int] = mapped_column(
        ForeignKey("projects.id"), nullable=False, index=True
    )


class Task(Base):
    """
    When our user makes a prompt - it's github issues. Agent will fetch tasks
    If  all the tasks in the database it's not really reproducible - not everything is in agents home.

    company goal - write facebook. that goes to the first task
    the composer runs after the project is created and is always running
    we can docker compose down that composer to set it up or docker compose up to get it running (NOT RLLY DOCKER)
    when the company is created NOT ONLY the composer starts running but also the task is created and placed in our DB
    tasks can ge generated by AI or by a user
    chat will be created right away as well after the user creates a company
    """

    __tablename__ = "tasks"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    content: Mapped[str] = mapped_column(Text, nullable=False)
    todos: Mapped[str] = mapped_column(
        Text, nullable=True
    )  # todos markdown format for agent long term memory
    project_id: Mapped[int] = mapped_column(
        ForeignKey("projects.id"), nullable=False, index=True
    )
    chat_id: Mapped[int] = mapped_column(
        ForeignKey("chats.id"), nullable=False, index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=datetime.now(UTC)
    )


class UserToProject(Base):  # fixed double space
    __tablename__ = "users_to_projects"

    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), primary_key=True)
    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"), primary_key=True)
    role: Mapped[int] = mapped_column(Integer, nullable=False)
